export const SHOW_SUCCESS_ALERT = 'SHOW_SUCCESS_ALERT';
export const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';
export const SHOW_WARNING_ALERT = 'SHOW_WARNING_ALERT';
export const SHOW_INFO_ALERT = 'SHOW_INFO_ALERT';